In [1]:
import pandas as pd

# reading data

In [2]:
df=pd.read_csv('data.csv')

In [3]:
df.head()

fever  BODYPAIN  age  runnyNose  diffBreath  infectionProb
0   98.660242         0   49          1          -1              0
1  101.342263         1   62          0          -1              1
2   99.908397         1   32          1           1              0
3   98.311599         1   65          0           0              0
4  101.317964         1   25          1           0              0

In [4]:
df.tail()

fever  BODYPAIN  age  runnyNose  diffBreath  infectionProb
1022   98.308677         1   38          1           1              1
1023   98.034353         1   38          0          -1              1
1024   98.823691         1   70          1          -1              0
1025   99.155619         1   68          1           0              0
1026  100.112244         1   48          0          -1              1

In [5]:
df.info

<bound method DataFrame.info of            fever  BODYPAIN  age  runnyNose  diffBreath  infectionProb
0      98.660242         0   49          1          -1              0
1     101.342263         1   62          0          -1              1
2      99.908397         1   32          1           1              0
3      98.311599         1   65          0           0              0
4     101.317964         1   25          1           0              0
...          ...       ...  ...        ...         ...            ...
1022   98.308677         1   38          1           1              1
1023   98.034353         1   38          0          -1              1
1024   98.823691         1   70          1          -1              0
1025   99.155619         1   68          1           0              0
1026  100.112244         1   48          0          -1              1

[1027 rows x 6 columns]>

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1027 entries, 0 to 1026
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fever          1027 non-null   float64
 1   BODYPAIN       1027 non-null   int64  
 2   age            1027 non-null   int64  
 3   runnyNose      1027 non-null   int64  
 4   diffBreath     1027 non-null   int64  
 5   infectionProb  1027 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 48.3 KB


In [7]:
df['diffBreath'].value_counts()

-1    354
 1    348
 0    325
Name: diffBreath, dtype: int64

In [8]:
df.describe()

fever     BODYPAIN          age    runnyNose   diffBreath  \
count  1027.000000  1027.000000  1027.000000  1027.000000  1027.000000   
mean     99.927925     0.492697    52.272639     0.509250    -0.005842   
std       1.136219     0.500190    16.245847     0.500158     0.827150   
min      98.008723     0.000000    25.000000     0.000000    -1.000000   
25%      98.937744     0.000000    38.000000     0.000000    -1.000000   
50%      99.946671     0.000000    52.000000     1.000000     0.000000   
75%     100.877482     1.000000    66.000000     1.000000     1.000000   
max     101.995686     1.000000    80.000000     1.000000     1.000000   

       infectionProb  
count    1027.000000  
mean        0.499513  
std         0.500243  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

# Train test splitting

In [9]:
import numpy as np

In [10]:
def data_split(data,ratio):
    np.random.seed(42)
    shuffled=np.random.permutation(len(data))
    test_set_size=int(len(data)*ratio)
    test_indices=shuffled[:test_set_size]
    train_indices=shuffled[test_set_size:]
    return data.iloc[train_indices],data.iloc[test_indices]

In [11]:
train,test=data_split(df,0.2)

In [12]:
train

fever  BODYPAIN  age  runnyNose  diffBreath  infectionProb
277   99.764357         1   72          0           0              0
622   99.154237         0   28          0          -1              0
265   99.093476         1   30          0           1              0
589   98.372985         1   52          0           1              0
467  101.390206         0   75          1          -1              0
..          ...       ...  ...        ...         ...            ...
330   98.812649         1   47          0           1              1
214  101.296235         1   45          1           0              0
466  100.339646         0   58          1           1              1
121  100.829421         0   43          1          -1              1
860   98.561292         1   58          0           1              1

[822 rows x 6 columns]

In [13]:
test

fever  BODYPAIN  age  runnyNose  diffBreath  infectionProb
428   99.691027         1   70          1           0              0
533   99.124993         0   42          0           0              0
388  101.821579         1   56          1          -1              1
107   99.819409         0   75          0          -1              1
423   99.557323         0   35          1          -1              0
..          ...       ...  ...        ...         ...            ...
110  100.598721         0   80          0           0              0
593   99.101063         0   57          1          -1              0
522   99.248453         1   76          1          -1              1
371  100.144122         1   41          1          -1              1
803   99.762217         0   25          1           0              1

[205 rows x 6 columns]

In [14]:
X_train=train[['fever','BODYPAIN','age','runnyNose','diffBreath']]

In [15]:
X_train

fever  BODYPAIN  age  runnyNose  diffBreath
277   99.764357         1   72          0           0
622   99.154237         0   28          0          -1
265   99.093476         1   30          0           1
589   98.372985         1   52          0           1
467  101.390206         0   75          1          -1
..          ...       ...  ...        ...         ...
330   98.812649         1   47          0           1
214  101.296235         1   45          1           0
466  100.339646         0   58          1           1
121  100.829421         0   43          1          -1
860   98.561292         1   58          0           1

[822 rows x 5 columns]

In [16]:
X_train

fever  BODYPAIN  age  runnyNose  diffBreath
277   99.764357         1   72          0           0
622   99.154237         0   28          0          -1
265   99.093476         1   30          0           1
589   98.372985         1   52          0           1
467  101.390206         0   75          1          -1
..          ...       ...  ...        ...         ...
330   98.812649         1   47          0           1
214  101.296235         1   45          1           0
466  100.339646         0   58          1           1
121  100.829421         0   43          1          -1
860   98.561292         1   58          0           1

[822 rows x 5 columns]

In [17]:
X_train=train[['fever','BODYPAIN','age','runnyNose','diffBreath']].to_numpy()

In [18]:
X_train

array([[ 99.76435687,   1.        ,  72.        ,   0.        ,
          0.        ],
       [ 99.15423731,   0.        ,  28.        ,   0.        ,
         -1.        ],
       [ 99.09347551,   1.        ,  30.        ,   0.        ,
          1.        ],
       ...,
       [100.3396462 ,   0.        ,  58.        ,   1.        ,
          1.        ],
       [100.8294206 ,   0.        ,  43.        ,   1.        ,
         -1.        ],
       [ 98.561292  ,   1.        ,  58.        ,   0.        ,
          1.        ]])

In [19]:
X_train=train[['fever','BODYPAIN','age','runnyNose','diffBreath']].to_numpy()
X_test=test[['fever','BODYPAIN','age','runnyNose','diffBreath']].to_numpy()

In [20]:
Y_train=train[['infectionProb']].to_numpy().reshape(822,)
Y_test=test[['infectionProb']].to_numpy().reshape(205,)

In [21]:
Y_train

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
clf=LogisticRegression()
clf.fit(X_train,Y_train)

LogisticRegression()

In [24]:
clf.predict([[100,1,22,1,1]])

array([1], dtype=int64)

In [25]:
clf.predict_proba([[100,1,22,1,1]])

array([[0.45516646, 0.54483354]])

In [28]:
inputfeatures=[100,1,22,1,1]
infection_probability=clf.predict_proba([inputfeatures])[0][1]


In [29]:
infection_probability

0.5448335378228214

In [30]:
inputfeatures=[108,1,22,1,1]
infection_probability=clf.predict_proba([inputfeatures])[0][1]


In [31]:
infection_probability

0.5444800508645095